name: CI on Mac

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: CI-Build
        run: |
          bash -x setup.sh
          make
